Example endpoint returning a prediction of iris data
---
  parameters:
    - name: text
      in: query
      type: string
      required: true
      description: string datatype
  responses:
    500:
      description: Error Please enter the correct input parameters
    200:
      description: Model Details for single prediction
      schema:
        id: Model output details for single prediction
        properties:
          Api Response:
            type: string
            description: prediction output for single row
            default: 'NA'
